### ISSUE TITLE
Message Display Issue in Web Viewer

### ISSUE THREAD

**Issue by PrimeTDMomega** [Ynfuien/MineflayerChatBot#1]
So when any messages are sent by the bot or the bot recieves any output of a command it displays fine on console but it returns
`[Object object]` in the web viewer.
![image](https://github.com/Ynfuien/MineflayerChatBot/assets/105910256/4109e668-5b93-4f2f-a831-8e4519913c8d)
While it appears correctly in console
![image](https://github.com/Ynfuien/MineflayerChatBot/assets/105910256/da3b5eca-91e7-48fe-8799-fd92012e61a2)
The account named `primexd` is the account being used

No error is displayed in console or webviewer.
THX

**Comment by Ynfuien** [comment]
Oh, my bad. Some of the code, for the next update, slipped through in the last commits, and broke messages. For now, fixed in the last [commit](https://github.com/Ynfuien/MineflayerChatBot/commit/337e3f0b1b6b53fcc18553da01a5f8a8dfc78c06). Thank you for noticing
